# Generated by Django 5.2.3 on 2025-06-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_rename_link_banner_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
