# Generated by Django 5.2.3 on 2025-06-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcolor_productsize_productimage_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='extra_product_images/'),
        ),
    ]
