# Generated by Django 5.2.3 on 2025-06-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wishlist_items',
            new_name='product',
        ),
    ]
