# Generated by Django 5.2.3 on 2025-06-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_banner_button_text'),
        ('wishlist', '0002_rename_wishlist_items_wishlistitem_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='WishlistProduct',
        ),
    ]
